# ----
# Site

title: Zumba Songkran Fiesta
url: "https://www.facebook.com/events/433432927075584/"
baseurl:
google_analytics_key: 
google_maps_javascript_api_key: "AIzaSyAfLRVePw8pQvZy7J8xTySJ0UCOBUhA5HQ"
eventbrite_embed: '<div style="width:100%; text-align:left;"><iframe src="https://eventbrite.com/tickets-external?eid=42792551674&ref=etckt" frameborder="0" height="300" width="100%" vspace="0" hspace="0" marginheight="5" marginwidth="5" scrolling="auto" allowtransparency="true"></iframe><div style="font-family:Helvetica, Arial; font-size:12px; padding:10px 0 5px; margin:2px; width:100%; text-align:left;" ></div></div>'
timezone: Asia/Bangkok

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: All ZIN in town
author:
  name: ZIN Hua Hin
  email: zin.huahin2018@gmail.com
  twitter: # twitter username without the @ symbol
social:
  name: Facebook
  links:
    - https://www.facebook.com/events/433432927075584/

# -----
# Build

timezone: Asia/Bangkok

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: page

# -----------
# CloudCannon

_comments:
  background_image: Image shown behind the content.
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  timezone: The timezone the event dates are listed in
